// Single entry point for all API services
export { authService, usersService } from './endpoints/auth.service'
export type { LoginPayload, ChangePasswordPayload, CreateUserPayload } from './endpoints/auth.service'
export { obrasService } from './endpoints/obras.service'
export type { CreateObraDto, CloseObraDto } from './endpoints/obras.service'
export { almacenesService } from './endpoints/almacenes.service'
export type { GetInventarioParams } from './endpoints/almacenes.service'
export { prestamosService } from './endpoints/prestamos.service'
export type { CreatePrestamoDto, GetPrestamosParams } from './endpoints/prestamos.service'
export { solicitudesService } from './endpoints/solicitudes.service'
export type { CreateSolicitudDto } from './endpoints/solicitudes.service'
export { transferenciasService } from './endpoints/transferencias.service'
export type { CreateTransferenciaDto, GetMovimientosParams } from './endpoints/transferencias.service'
export { sectorizacionService } from './endpoints/sectorizacion.service'
export type { CreateSectorizacionDto } from './endpoints/sectorizacion.service'
export { reportesService } from './endpoints/reportes.service'
export type { GetReportesParams } from './endpoints/reportes.service'
export { apiClient, HttpError } from './api/client'
