// Single entry point for all API services
export { authService, usersService } from './endpoints/auth.service'
export type { LoginPayload, ChangePasswordPayload, CreateUserPayload, UpdateUserPayload, UpdateCredentialsPayload } from './endpoints/auth.service'
export { obrasService } from './endpoints/obras.service'
export type { CreateObraDto, UpdateObraDto, CloseObraDto } from './endpoints/obras.service'
export { almacenesService } from './endpoints/almacenes.service'
export type { CreateAlmacenDto, UpdateAlmacenDto, GetInventarioParams } from './endpoints/almacenes.service'
export { inventarioService } from './endpoints/inventario.service'
export type { CreateItemDto, UpdateItemDto, SetAlmacenStockDto, CreateEntradaStockDto, AlmacenItemResponse } from './endpoints/inventario.service'
export { categoriasService } from './endpoints/categorias.service'
export type { CreateCategoriaDto, UpdateCategoriaDto } from './endpoints/categorias.service'
export { proveedoresService } from './endpoints/proveedores.service'
export type { CreateProveedorDto, UpdateProveedorDto } from './endpoints/proveedores.service'
export { prestamosService } from './endpoints/prestamos.service'
export type { CreatePrestamoPayload, DevolverPrestamoPayload, GetPrestamosParams } from './endpoints/prestamos.service'
export { solicitudesService } from './endpoints/solicitudes.service'
export type { CreateSolicitudDto, CreateContratistaDto, ItemDisponible } from './endpoints/solicitudes.service'
export { transferenciasService } from './endpoints/transferencias.service'
export type { CreateTransferenciaDto, TransferenciaResponse, TransferenciaItemDto, GetTransferenciasParams } from './endpoints/transferencias.service'
export { sectorizacionService } from './endpoints/sectorizacion.service'
export type { CreateSectorizacionDto, UpdateSectorizacionDto } from './endpoints/sectorizacion.service'
export { reportesService } from './endpoints/reportes.service'
export type { GetReportesParams } from './endpoints/reportes.service'
export { bajasService } from './endpoints/bajas.service'
export type { CreateBajaPayload } from './endpoints/bajas.service'
export { aprobacionesService } from './endpoints/aprobaciones.service'
export type { CrearEdicionInventarioPayload } from './endpoints/aprobaciones.service'
export { consumoService } from './endpoints/consumo.service'
export type { ConsumoRecord, SaveConsumoDto, ConsumoValueDto } from './endpoints/consumo.service'
export { apiClient, HttpError } from './api/client'
